import { Filter } from './interfaces/interface';

export const product: Filter[] = [
  { 
    'name': 'Жемчужная магия',
    'price': '30$',
    'year': '2022',
    'offer': 'Популярное',
    'decoration': 'Браслет',
    'typeInsert': 'Жемчуг',
    'typeMetall': 'Золото',
    'image': '../../../assets/catalog/bracelets/1.JPG',
  },
  { 
    'name': 'Для шармов браслет',
    'price': '30$',
    'year': '2022',
    'offer': 'Новинка',
    'decoration': 'Браслет',
    'typeInsert': 'Без вставки',
    'typeMetall': 'Золото',
    'image': '../../../assets/catalog/bracelets/8.JPG',
  },
  { 
    'name': 'Жемчужная россыпь',
    'price': '30$',
    'year': '2022',
    'offer': 'Новинка',
    'decoration': 'Браслет',
    'typeInsert': 'Жемчуг',
    'typeMetall': 'Золото',
    'image': '../../../assets/catalog/bracelets/9.JPG',
  },
  { 
    'name': 'Rock-n-roll',
    'price': '20$',
    'year': '2022',
    'offer': 'Популярное',
    'decoration': 'Браслет',
    'typeInsert': 'Без вставки',
    'typeMetall': 'Золото',
    'image': '../../../assets/catalog/bracelets/2.JPG',
  },
  { 
    'name': 'Нежность',
    'price': '70$',
    'year': '2022',
    'offer': 'Популярное',
    'decoration': 'Браслет',
    'typeInsert': 'Фианит',
    'typeMetall': 'Серебро',
    'image': '../../../assets/catalog/bracelets/3.JPG',
  },
  // { 
  //   'name': 'Весна',
  //   'price': '30$',
  //   'year': '2020',
  //   'offer': 'Популярное',
  //   'decoration': 'Браслет',
  //   'typeInsert': 'Бриллиант',
  //   'typeMetall': 'Золото',
  //   'image': '../../../assets/catalog/bracelets/4.JPG',
  // },
  // { 
  //   'name': 'Капля',
  //   'price': '10$',
  //   'year': '2021',
  //   'offer': 'Новинка',
  //   'decoration': 'Браслет',
  //   'typeInsert': 'Фианит',
  //   'typeMetall': 'Серебро',
  //   'image': '../../../assets/catalog/bracelets/5.JPG',
  // },
  // { 
  //   'name': 'Любовь',
  //   'price': '100$',
  //   'year': '2022',
  //   'offer': 'Новинка',
  //   'decoration': 'Браслет',
  //   'typeInsert': 'Бриллиант',
  //   'typeMetall': 'Золото',
  //   'image': '../../../assets/catalog/bracelets/6.JPG',
  // },
  // { 
  //   'name': 'Комплект браслетов',
  //   'price': '50$',
  //   'year': '2020',
  //   'offer': false,
  //   'decoration': 'Браслет',
  //   'typeInsert': 'Фианит',
  //   'typeMetall': 'Серебро',
  //   'image': '../../../assets/catalog/bracelets/7.JPG',
  // },
  // { 
  //   'name': 'Браслет с фианитами',
  //   'price': '50$',
  //   'year': '2020',
  //   'offer': 'Новинка',
  //   'decoration': 'Браслет',
  //   'typeInsert': 'Фианит',
  //   'typeMetall': 'Золото',
  //   'image': '../../../assets/catalog/bracelets/10.JPG',
  // },
  // { 
  //   'name': 'Браслет с фианитами',
  //   'price': '50$',
  //   'year': '2020',
  //   'offer': 'Популярное',
  //   'decoration': 'Браслет',
  //   'typeInsert': 'Фианит',
  //   'typeMetall': 'Золото',
  //   'image': '../../../assets/catalog/bracelets/11.JPG',
  // },
  // { 
  //   'name': 'Браслет',
  //   'price': '50$',
  //   'year': '2020',
  //   'offer': 'Новинка',
  //   'decoration': 'Браслет',
  //   'typeInsert': 'Без вставки',
  //   'typeMetall': 'Серебро',
  //   'image': '../../../assets/catalog/bracelets/12.JPG',
  // },
  // { 
  //   'name': 'Браслет',
  //   'price': '50$',
  //   'year': '2020',
  //   'offer': 'Новинка',
  //   'decoration': 'Браслет',
  //   'typeInsert': 'Бриллиант',
  //   'typeMetall': 'Серебро',
  //   'image': '../../../assets/catalog/bracelets/13.JPG',
  // },
  // { 
  //   'name': 'Браслет',
  //   'price': '50$',
  //   'year': '2020',
  //   'offer': 'Новинка',
  //   'decoration': 'Браслет',
  //   'typeInsert': 'Жемчуг',
  //   'typeMetall': 'Серебро',
  //   'image': '../../../assets/catalog/bracelets/14.JPG',
  // },
  // { 
  //   'name': 'Браслет',
  //   'price': '50$',
  //   'year': '2020',
  //   'offer': 'Новинка',
  //   'decoration': 'Браслет',
  //   'typeInsert': 'Без вставки',
  //   'typeMetall': 'Серебро',
  //   'image': '../../../assets/catalog/bracelets/15.JPG',
  // },
  // { 
  //   'name': 'Браслет',
  //   'price': '50$',
  //   'year': '2020',
  //   'offer': 'Популярное',
  //   'decoration': 'Браслет',
  //   'typeInsert': 'Бриллиант',
  //   'typeMetall': 'Серебро',
  //   'image': '../../../assets/catalog/bracelets/16.JPG',
  // },
  // { 
  //   'name': 'Браслет',
  //   'price': '50$',
  //   'year': '2020',
  //   'offer': 'Популярное',
  //   'decoration': 'Браслет',
  //   'typeInsert': 'Жемчуг',
  //   'typeMetall': 'Серебро',
  //   'image': '../../../assets/catalog/bracelets/17.JPG',
  // },


  // { 
  //   'name': 'Face',
  //   'price': '200$',
  //   'year': '2022',
  //   'offer': false,
  //   'decoration': 'Цепочка',
  //   'typeInsert': 'Без вставки',
  //   'typeMetall': 'Золото',
  //   'image': '../../../assets/catalog/chains/1.JPG',
  // },
  // { 
  //   'name': 'Fog',
  //   'price': '200$',
  //   'year': '2022',
  //   'offer': 'Популярное',
  //   'decoration': 'Цепочка',
  //   'typeInsert': 'Бриллиант',
  //   'typeMetall': 'Золото',
  //   'image': '../../../assets/catalog/chains/12.JPG',
  // },
  // { 
  //   'name': 'Cloud',
  //   'price': '200$',
  //   'year': '2022',
  //   'offer': 'Популярное',
  //   'decoration': 'Цепочка',
  //   'typeInsert': 'Фианит',
  //   'typeMetall': 'Золото',
  //   'image': '../../../assets/catalog/chains/13.JPG',
  // },
  // { 
  //   'name': 'Магия',
  //   'price': '100$',
  //   'year': '2022',
  //   'offer': 'Новинка',
  //   'decoration': 'Цепочка',
  //   'typeInsert': 'Без вставки',
  //   'typeMetall': 'Серебро',
  //   'image': '../../../assets/catalog/chains/2.JPG',
  // },
  // { 
  //   'name': 'Искусство',
  //   'price': '100$',
  //   'year': '2021',
  //   'offer': false,
  //   'decoration': 'Цепочка',
  //   'typeInsert': 'Без вставки',
  //   'typeMetall': 'Серебро',
  //   'image': '../../../assets/catalog/chains/3.JPG',
  // },
  // { 
  //   'name': 'Искусство',
  //   'price': '100$',
  //   'year': '2021',
  //   'offer': 'Новинка',
  //   'decoration': 'Цепочка',
  //   'typeInsert': 'Бриллиант',
  //   'typeMetall': 'Серебро',
  //   'image': '../../../assets/catalog/chains/15.JPG',
  // },
  // { 
  //   'name': 'Искусство',
  //   'price': '100$',
  //   'year': '2021',
  //   'offer': 'Новинка',
  //   'decoration': 'Цепочка',
  //   'typeInsert': 'Фианит',
  //   'typeMetall': 'Серебро',
  //   'image': '../../../assets/catalog/chains/16.JPG',
  // },
  // { 
  //   'name': 'Искусство',
  //   'price': '100$',
  //   'year': '2021',
  //   'offer': 'Новинка',
  //   'decoration': 'Цепочка',
  //   'typeInsert': 'Жемчуг',
  //   'typeMetall': 'Серебро',
  //   'image': '../../../assets/catalog/chains/17.JPG',
  // },
  // { 
  //   'name': 'Искусство',
  //   'price': '100$',
  //   'year': '2021',
  //   'offer': 'Популярное',
  //   'decoration': 'Цепочка',
  //   'typeInsert': 'Бриллиант',
  //   'typeMetall': 'Серебро',
  //   'image': '../../../assets/catalog/chains/18.JPG',
  // },
  // { 
  //   'name': 'Искусство',
  //   'price': '100$',
  //   'year': '2021',
  //   'offer': 'Популярное',
  //   'decoration': 'Цепочка',
  //   'typeInsert': 'Фианит',
  //   'typeMetall': 'Серебро',
  //   'image': '../../../assets/catalog/chains/19.JPG',
  // },
  // { 
  //   'name': 'Искусство',
  //   'price': '100$',
  //   'year': '2021',
  //   'offer': 'Популярное',
  //   'decoration': 'Цепочка',
  //   'typeInsert': 'Жемчуг',
  //   'typeMetall': 'Серебро',
  //   'image': '../../../assets/catalog/chains/19.JPG',
  // },
  // { 
  //   'name': 'Любовь навечно',
  //   'price': '157$',
  //   'year': '2021',
  //   'offer': false,
  //   'decoration': 'Цепочка',
  //   'typeInsert': 'Без вставки',
  //   'typeMetall': 'Золото',
  //   'image': '../../../assets/catalog/chains/4.JPG',
  // },
  // { 
  //   'name': 'Университетский стиль',
  //   'price': '60$',
  //   'year': '2022',
  //   'offer': 'Популярное',
  //   'decoration': 'Цепочка',
  //   'typeInsert': 'Без вставки',
  //   'typeMetall': 'Серебро',
  //   'image': '../../../assets/catalog/chains/5.JPG',
  // },
  // { 
  //   'name': 'Торжество',
  //   'price': '180$',
  //   'year': '2021',
  //   'offer': false,
  //   'decoration': 'Цепочка',
  //   'typeInsert': 'Фианит',
  //   'typeMetall': 'Золото',
  //   'image': '../../../assets/catalog/chains/6.JPG',
  // },
  // { 
  //   'name': 'Moon',
  //   'price': '200$',
  //   'year': '2022',
  //   'offer': 'Новинка',
  //   'decoration': 'Цепочка',
  //   'typeInsert': 'Без вставки',
  //   'typeMetall': 'Золото',
  //   'image': '../../../assets/catalog/chains/7.JPG',
  // },
  // { 
  //   'name': 'Закат',
  //   'price': '120$',
  //   'year': '2022',
  //   'offer': 'Новинка',
  //   'decoration': 'Цепочка',
  //   'typeInsert': 'Жемчуг',
  //   'typeMetall': 'Золото',
  //   'image': '../../../assets/catalog/chains/8.JPG',
  // },
  // { 
  //   'name': 'Инь & Янь"',
  //   'price': '80$',
  //   'year': '2021',
  //   'offer': 'Популярное',
  //   'decoration': 'Цепочка',
  //   'typeInsert': 'Жемчуг',
  //   'typeMetall': 'Золото',
  //   'image': '../../../assets/catalog/chains/9.JPG',
  // },
  // { 
  //   'name': 'Сердце Эвереста',
  //   'price': '110$',
  //   'year': '2021',
  //   'offer': 'Новинка',
  //   'decoration': 'Цепочка',
  //   'typeInsert': 'Фианит',
  //   'typeMetall': 'Золото',
  //   'image': '../../../assets/catalog/chains/10.JPG',
  // },
  // { 
  //   'name': 'Sun',
  //   'price': '110$',
  //   'year': '2021',
  //   'offer': 'Новинка',
  //   'decoration': 'Цепочка',
  //   'typeInsert': 'Бриллиант',
  //   'typeMetall': 'Золото',
  //   'image': '../../../assets/catalog/chains/11.JPG',
  // },
  // { 
  //   'name': 'Face',
  //   'price': '200$',
  //   'year': '2022',
  //   'offer': 'Популярное',
  //   'decoration': 'Цепочка',
  //   'typeInsert': 'Без вставки',
  //   'typeMetall': 'Золото',
  //   'image': '../../../assets/catalog/chains/14.JPG',
  // },
  // { 
  //   'name': 'Эверест',
  //   'price': '200$',
  //   'year': '2021',
  //   'offer': false,
  //   'decoration': 'Серьги',
  //   'typeInsert': 'Без вставки',
  //   'typeMetall': 'Золото',
  //   'image': '../../../assets/catalog/earrings/1.JPG',
  // },
  // { 
  //   'name': 'Эверест',
  //   'price': '200$',
  //   'year': '2021',
  //   'offer': 'Популярное',
  //   'decoration': 'Серьги',
  //   'typeInsert': 'Бриллиант',
  //   'typeMetall': 'Золото',
  //   'image': '../../../assets/catalog/earrings/17.JPG',
  // },
  // { 
  //   'name': 'Эверест',
  //   'price': '200$',
  //   'year': '2021',
  //   'offer': 'Популярное',
  //   'decoration': 'Серьги',
  //   'typeInsert': 'Фианит',
  //   'typeMetall': 'Серебро',
  //   'image': '../../../assets/catalog/earrings/18.JPG',
  // },
  // { 
  //   'name': 'Эверест',
  //   'price': '200$',
  //   'year': '2021',
  //   'offer': 'Популярное',
  //   'decoration': 'Серьги',
  //   'typeInsert': 'Жемчуг',
  //   'typeMetall': 'Серебро',
  //   'image': '../../../assets/catalog/earrings/19.JPG',
  // },
  // { 
  //   'name': 'Рок',
  //   'price': '200$',
  //   'year': '2019',
  //   'offer': false,
  //   'decoration': 'Серьги',
  //   'typeInsert': 'Без вставки',
  //   'typeMetall': 'Золото',
  //   'image': '../../../assets/catalog/earrings/2.JPG',
  // },
  // { 
  //   'name': 'Изящность"',
  //   'price': '40$',
  //   'year': '2021',
  //   'offer': false,
  //   'decoration': 'Серьги',
  //   'typeInsert': 'Без вставки',
  //   'typeMetall': 'Золото',
  //   'image': '../../../assets/catalog/earrings/3.JPG',
  // },
  // { 
  //   'name': 'Стиляга',
  //   'price': '30$',
  //   'year': '2022',
  //   'offer': 'Новинка',
  //   'decoration': 'Серьги',
  //   'typeInsert': 'Без вставки',
  //   'typeMetall': 'Золото',
  //   'image': '../../../assets/catalog/earrings/4.JPG',
  // },
  // { 
  //   'name': 'Стиляга',
  //   'price': '30$',
  //   'year': '2022',
  //   'offer': 'Популярное',
  //   'decoration': 'Серьги',
  //   'typeInsert': 'Бриллиант',
  //   'typeMetall': 'Серебро',
  //   'image': '../../../assets/catalog/earrings/25.JPG',
  // },
  // { 
  //   'name': 'Листья',
  //   'price': '60$',
  //   'year': '2020',
  //   'offer': 'Популярное',
  //   'decoration': 'Серьги',
  //   'typeInsert': 'Без вставки',
  //   'typeMetall': 'Золото',
  //   'image': '../../../assets/catalog/earrings/5.JPG',
  // },
  // { 
  //   'name': 'Невеста',
  //   'price': '200$',
  //   'year': '2021',
  //   'offer': false,
  //   'decoration': 'Серьги',
  //   'typeInsert': 'Без вставки',
  //   'typeMetall': 'Золото',
  //   'image': '../../../assets/catalog/earrings/6.JPG',
  // },
  // { 
  //   'name': 'Элегантность',
  //   'price': '110$',
  //   'year': '2021',
  //   'offer': 'Новинка',
  //   'decoration': 'Серьги',
  //   'typeInsert': 'Фианит',
  //   'typeMetall': 'Серебро',
  //   'image': '../../../assets/catalog/earrings/7.JPG',
  // },
  // { 
  //   'name': 'Радость',
  //   'price': '180$',
  //   'year': '2022',
  //   'offer': false,
  //   'decoration': 'Серьги',
  //   'typeInsert': 'Бриллиант',
  //   'typeMetall': 'Золото',
  //   'image': '../../../assets/catalog/earrings/8.JPG',
  // },
  // { 
  //   'name': 'Гвоздики',
  //   'price': '180$',
  //   'year': '2022',
  //   'offer': 'Новинка',
  //   'decoration': 'Серьги',
  //   'typeInsert': 'Бриллиант',
  //   'typeMetall': 'Золото',
  //   'image': '../../../assets/catalog/earrings/14.JPG',
  // },
  // { 
  //   'name': 'Висюльки',
  //   'price': '180$',
  //   'year': '2022',
  //   'offer': 'Новинка',
  //   'decoration': 'Серьги',
  //   'typeInsert': 'Жемчуг',
  //   'typeMetall': 'Золото',
  //   'image': '../../../assets/catalog/earrings/15.JPG',
  // },
  // { 
  //   'name': 'Замочек',
  //   'price': '80$',
  //   'year': '2022',
  //   'offer': 'Новинка',
  //   'decoration': 'Серьги',
  //   'typeInsert': 'Фианит',
  //   'typeMetall': 'Золото',
  //   'image': '../../../assets/catalog/earrings/16.JPG',
  // },
  // { 
  //   'name': 'Power',
  //   'price': '20$',
  //   'year': '2018',
  //   'offer': 'Новинка',
  //   'decoration': 'Серьги',
  //   'typeInsert': 'Без вставки',
  //   'typeMetall': 'Серебро',
  //   'image': '../../../assets/catalog/earrings/9.JPG',
  // },
  // { 
  //   'name': 'Elegance',
  //   'price': '100$',
  //   'year': '2022',
  //   'offer': false,
  //   'decoration': 'Серьги',
  //   'typeInsert': 'Без вставки',
  //   'typeMetall': 'Золото',
  //   'image': '../../../assets/catalog/earrings/11.JPG',
  // },
  // { 
  //   'name': 'Шик',
  //   'price': '100$',
  //   'year': '2022',
  //   'offer': 'Популярное',
  //   'decoration': 'Серьги',
  //   'typeInsert': 'Фианит',
  //   'typeMetall': 'Золото',
  //   'image': '../../../assets/catalog/earrings/20.JPG',
  // },
  // { 
  //   'name': 'Шик',
  //   'price': '100$',
  //   'year': '2022',
  //   'offer': 'Новинка',
  //   'decoration': 'Серьги',
  //   'typeInsert': 'Жемчуг',
  //   'typeMetall': 'Серебро',
  //   'image': '../../../assets/catalog/earrings/23.JPG',
  // },
  // { 
  //   'name': 'Шик',
  //   'price': '100$',
  //   'year': '2022',
  //   'offer': 'Популярное',
  //   'decoration': 'Серьги',
  //   'typeInsert': 'Без вставки',
  //   'typeMetall': 'Серебро',
  //   'image': '../../../assets/catalog/earrings/24.JPG',
  // },
  // { 
  //   'name': 'Snow',
  //   'price': '100$',
  //   'year': '2022',
  //   'offer': 'Популярное',
  //   'decoration': 'Серьги',
  //   'typeInsert': 'Жемчуг',
  //   'typeMetall': 'Золото',
  //   'image': '../../../assets/catalog/earrings/21.JPG',
  // },
  // { 
  //   'name': 'Snow',
  //   'price': '100$',
  //   'year': '2022',
  //   'offer': 'Новинка',
  //   'decoration': 'Серьги',
  //   'typeInsert': 'Бриллиант',
  //   'typeMetall': 'Серебро',
  //   'image': '../../../assets/catalog/earrings/22.JPG',
  // },
  // { 
  //   'name': 'Рим',
  //   'price': '200$',
  //   'year': '2022',
  //   'offer': 'Новинка',
  //   'decoration': 'Заколка',
  //   'typeInsert': 'Без вставки',
  //   'typeMetall': 'Золото',
  //   'image': '../../../assets/catalog/hairpins/1.JPG',
  // },
  // { 
  //   'name': 'King',
  //   'price': '200$',
  //   'year': '2022',
  //   'offer': 'Популярное',
  //   'decoration': 'Заколка',
  //   'typeInsert': 'Бриллиант',
  //   'typeMetall': 'Серебро',
  //   'image': '../../../assets/catalog/hairpins/15.JPG',
  // },
  // { 
  //   'name': 'Бабочка',
  //   'price': '200$',
  //   'year': '2022',
  //   'offer': 'Популярное',
  //   'decoration': 'Заколка',
  //   'typeInsert': 'Фианит',
  //   'typeMetall': 'Серебро',
  //   'image': '../../../assets/catalog/hairpins/16.JPG',
  // },
  // { 
  //   'name': 'Набор заколок',
  //   'price': '30$',
  //   'year': '2021',
  //   'offer': 'Новинка',
  //   'decoration': 'Заколка',
  //   'typeInsert': 'Жемчуг',
  //   'typeMetall': 'Золото',
  //   'image': '../../../assets/catalog/hairpins/2.JPG',
  // },
  // { 
  //   'name': 'Берег',
  //   'price': '40$',
  //   'year': '2022',
  //   'offer': 'Популярное',
  //   'decoration': 'Заколка',
  //   'typeInsert': 'Жемчуг',
  //   'typeMetall': 'Серебро',
  //   'image': '../../../assets/catalog/hairpins/3.JPG',
  // },
  // { 
  //   'name': 'Цветок',
  //   'price': '50$',
  //   'year': '2022',
  //   'offer': 'Популярное',
  //   'decoration': 'Заколка',
  //   'typeInsert': 'Жемчуг',
  //   'typeMetall': 'Серебро',
  //   'image': '../../../assets/catalog/hairpins/4.JPG',
  // },
  // { 
  //   'name': 'Style',
  //   'price': '60$',
  //   'year': '2021',
  //   'offer': 'Новинка',
  //   'decoration': 'Заколка',
  //   'typeInsert': 'Жемчуг',
  //   'typeMetall': 'Серебро',
  //   'image': '../../../assets/catalog/hairpins/5.JPG',
  // },
  // { 
  //   'name': 'New Style',
  //   'price': '20$',
  //   'year': '2022',
  //   'offer': false,
  //   'decoration': 'Заколка',
  //   'typeInsert': 'Жемчуг',
  //   'typeMetall': 'Серебро',
  //   'image': '../../../assets/catalog/hairpins/6.JPG',
  // },
  // { 
  //   'name': 'Summer',
  //   'price': '20$',
  //   'year': '2020',
  //   'offer': 'Популярное',
  //   'decoration': 'Заколка',
  //   'typeInsert': 'Жемчуг',
  //   'typeMetall': 'Золото',
  //   'image': '../../../assets/catalog/hairpins/7.JPG',
  // },
  // { 
  //   'name': 'Summer',
  //   'price': '20$',
  //   'year': '2020',
  //   'offer': 'Популярное',
  //   'decoration': 'Заколка',
  //   'typeInsert': 'Без вставки',
  //   'typeMetall': 'Серебро',
  //   'image': '../../../assets/catalog/hairpins/18.JPG',
  // },
  // { 
  //   'name': 'Evening',
  //   'price': '30$',
  //   'year': '2022',
  //   'offer': false,
  //   'decoration': 'Заколка',
  //   'typeInsert': 'Жемчуг',
  //   'typeMetall': 'Серебро',
  //   'image': '../../../assets/catalog/hairpins/8.JPG',
  // },
  // { 
  //   'name': 'Sea',
  //   'price': '200$',
  //   'year': '2021',
  //   'offer': false,
  //   'decoration': 'Заколка',
  //   'typeInsert': 'Жемчуг',
  //   'typeMetall': 'Серебро',
  //   'image': '../../../assets/catalog/hairpins/9.JPG',
  // },
  // { 
  //   'name': 'Комплект заколок',
  //   'price': '70$',
  //   'year': '2022',
  //   'offer': false,
  //   'decoration': 'Заколка',
  //   'typeInsert': 'Без вставки',
  //   'typeMetall': 'Золото',
  //   'image': '../../../assets/catalog/hairpins/10.JPG',
  // },
  // { 
  //   'name': 'Булавка',
  //   'price': '80$',
  //   'year': '2022',
  //   'offer': 'Новинка',
  //   'decoration': 'Заколка',
  //   'typeInsert': 'Без вставки',
  //   'typeMetall': 'Золото',
  //   'image': '../../../assets/catalog/hairpins/11.JPG',
  // },
  // { 
  //   'name': 'Невидимка',
  //   'price': '80$',
  //   'year': '2022',
  //   'offer': 'Новинка',
  //   'decoration': 'Заколка',
  //   'typeInsert': 'Бриллиант',
  //   'typeMetall': 'Серебро',
  //   'image': '../../../assets/catalog/hairpins/13.JPG',
  // },
  // { 
  //   'name': 'Невидимка',
  //   'price': '80$',
  //   'year': '2022',
  //   'offer': 'Новинка',
  //   'decoration': 'Заколка',
  //   'typeInsert': 'Фианит',
  //   'typeMetall': 'Серебро',
  //   'image': '../../../assets/catalog/hairpins/14.JPG',
  // },
  // { 
  //   'name': 'Star',
  //   'price': '80$',
  //   'year': '2022',
  //   'offer': 'Новинка',
  //   'decoration': 'Заколка',
  //   'typeInsert': 'Бриллиант',
  //   'typeMetall': 'Золото',
  //   'image': '../../../assets/catalog/hairpins/17.JPG',
  // },
  // { 
  //   'name': 'Star1',
  //   'price': '80$',
  //   'year': '2022',
  //   'offer': 'Новинка',
  //   'decoration': 'Заколка',
  //   'typeInsert': 'Фианит',
  //   'typeMetall': 'Золото',
  //   'image': '../../../assets/catalog/hairpins/18.JPG',
  // },
  // { 
  //   'name': 'Star1',
  //   'price': '80$',
  //   'year': '2022',
  //   'offer': 'Популярное',
  //   'decoration': 'Заколка',
  //   'typeInsert': 'Без вставки',
  //   'typeMetall': 'Золото',
  //   'image': '../../../assets/catalog/hairpins/19.JPG',
  // },
  // { 
  //   'name': 'Star1',
  //   'price': '80$',
  //   'year': '2022',
  //   'offer': 'Популярное',
  //   'decoration': 'Заколка',
  //   'typeInsert': 'Бриллиант',
  //   'typeMetall': 'Золото',
  //   'image': '../../../assets/catalog/hairpins/20.JPG',
  // },
  // { 
  //   'name': 'Sweet',
  //   'price': '80$',
  //   'year': '2022',
  //   'offer': 'Популярное',
  //   'decoration': 'Заколка',
  //   'typeInsert': 'Фианит',
  //   'typeMetall': 'Золото',
  //   'image': '../../../assets/catalog/hairpins/21.JPG',
  // },
  // { 
  //   'name': 'Air',
  //   'price': '150$',
  //   'year': '2020',
  //   'offer': 'Новинка',
  //   'decoration': 'Кольцо',
  //   'typeInsert': 'Бриллиант',
  //   'typeMetall': 'Серебро',
  //   'image': '../../../assets/catalog/rings/1.JPG',
  // },
  // { 
  //   'name': 'Spring',
  //   'price': '130$',
  //   'year': '2022',
  //   'offer': 'Популярное',
  //   'decoration': 'Кольцо',
  //   'typeInsert': 'Фианит',
  //   'typeMetall': 'Серебро',
  //   'image': '../../../assets/catalog/rings/2.JPG',
  // },
  // { 
  //   'name': 'Together',
  //   'price': '190$',
  //   'year': '2022',
  //   'offer': 'Новинка',
  //   'decoration': 'Кольцо',
  //   'typeInsert': 'Фианит',
  //   'typeMetall': 'Серебро',
  //   'image': '../../../assets/catalog/rings/3.JPG',
  // },
  // { 
  //   'name': 'Engagement',
  //   'price': '200$',
  //   'year': '2022',
  //   'offer': false,
  //   'decoration': 'Кольцо',
  //   'typeInsert': 'Бриллиант',
  //   'typeMetall': 'Серебро',
  //   'image': '../../../assets/catalog/rings/4.JPG',
  // },
  // { 
  //   'name': 'Роскошь',
  //   'price': '200$',
  //   'year': '2022',
  //   'offer': 'Новинка',
  //   'decoration': 'Кольцо',
  //   'typeInsert': 'Бриллиант',
  //   'typeMetall': 'Золото',
  //   'image': '../../../assets/catalog/rings/5.JPG',
  // },
  // { 
  //   'name': 'Счастье',
  //   'price': '180$',
  //   'year': '2020',
  //   'offer': false,
  //   'decoration': 'Кольцо',
  //   'typeInsert': 'Фианит',
  //   'typeMetall': 'Серебро',
  //   'image': '../../../assets/catalog/rings/6.JPG',
  // },
  // { 
  //   'name': 'Spring',
  //   'price': '100$',
  //   'year': '2022',
  //   'offer': 'Популярное',
  //   'decoration': 'Кольцо',
  //   'typeInsert': 'Фианит',
  //   'typeMetall': 'Золото',
  //   'image': '../../../assets/catalog/rings/7.JPG',
  // },
  // { 
  //   'name': 'Love',
  //   'price': '200$',
  //   'year': '2022',
  //   'offer': false,
  //   'decoration': 'Кольцо',
  //   'typeInsert': 'Фианит',
  //   'typeMetall': 'Серебро',
  //   'image': '../../../assets/catalog/rings/8.JPG',
  // },
  // { 
  //   'name': 'Happy',
  //   'price': '200$',
  //   'year': '2022',
  //   'offer': 'Популярное',
  //   'decoration': 'Кольцо',
  //   'typeInsert': 'Бриллиант',
  //   'typeMetall': 'Золото',
  //   'image': '../../../assets/catalog/rings/10.JPG',
  // },
  // { 
  //   'name': 'Бесконечность',
  //   'price': '20$',
  //   'year': '2022',
  //   'offer': 'Новинка',
  //   'decoration': 'Кольцо',
  //   'typeInsert': 'Без вставки',
  //   'typeMetall': 'Серебро',
  //   'image': '../../../assets/catalog/rings/11.JPG',
  // },
  // { 
  //   'name': 'Находка',
  //   'price': '50$',
  //   'year': '2022',
  //   'offer': 'Новинка',
  //   'decoration': 'Кольцо',
  //   'typeInsert': 'Жемчуг',
  //   'typeMetall': 'Серебро',
  //   'image': '../../../assets/catalog/rings/12.JPG',
  // },
  // { 
  //   'name': 'Королева',
  //   'price': '60$',
  //   'year': '2022',
  //   'offer': 'Популярное',
  //   'decoration': 'Кольцо',
  //   'typeInsert': 'Без вставки',
  //   'typeMetall': 'Серебро',
  //   'image': '../../../assets/catalog/rings/13.JPG',
  // },
  // { 
  //   'name': 'Old School',
  //   'price': '40$',
  //   'year': '2022',
  //   'offer': 'Популярное',
  //   'decoration': 'Кольцо',
  //   'typeInsert': 'Жемчуг',
  //   'typeMetall': 'Золото',
  //   'image': '../../../assets/catalog/rings/14.JPG',
  // },
  // { 
  //   'name': 'Обручальное кольцо мужское',
  //   'price': '40$',
  //   'year': '2022',
  //   'offer': 'Новинка',
  //   'decoration': 'Кольцо',
  //   'typeInsert': 'Без вставки',
  //   'typeMetall': 'Золото',
  //   'image': '../../../assets/catalog/rings/15.JPG',
  // },
  // { 
  //   'name': 'Помолвочное кольцо',
  //   'price': '40$',
  //   'year': '2022',
  //   'offer': 'Новинка',
  //   'decoration': 'Кольцо',
  //   'typeInsert': 'Фианит',
  //   'typeMetall': 'Золото',
  //   'image': '../../../assets/catalog/rings/16.JPG',
  // },
  // { 
  //   'name': 'Жемчужный омут',
  //   'price': '40$',
  //   'year': '2022',
  //   'offer': 'Новинка',
  //   'decoration': 'Кольцо',
  //   'typeInsert': 'Жемчуг',
  //   'typeMetall': 'Золото',
  //   'image': '../../../assets/catalog/rings/17.JPG',
  // },
  // { 
  //   'name': 'Женское обручальное кольцо',
  //   'price': '40$',
  //   'year': '2022',
  //   'offer': 'Популярное',
  //   'decoration': 'Кольцо',
  //   'typeInsert': 'Без вставки',
  //   'typeMetall': 'Золото',
  //   'image': '../../../assets/catalog/rings/18.JPG',
  // },
];