import ProductInformation from './interfaces/interface';

export const goods: ProductInformation[] = [
  { 
    name: 'Rock-n-roll',
    price: 20,
    year: 2010,
    offer: 'Популярное',
    decoration: 'Браслет',
    insert: 'Без вставки',
    metall: 'Золото',
    image: './assets/catalog/bracelets/1.JPG',
  },
  { 
    name: 'Нежность',
    price: 70,
    year: 2011,
    offer: 'Популярное',
    decoration: 'Браслет',
    insert: 'Фианит',
    metall: 'Серебро',
    image: './assets/catalog/bracelets/2.JPG',
  },
  { 
    name: 'Капля',
    price: 45,
    year: 2022,
    offer: 'Новинка',
    decoration: 'Браслет',
    insert: 'Фианит',
    metall: 'Серебро',
    image: './assets/catalog/bracelets/3.JPG',
  },
  { 
    name: 'Любовь',
    price: 100,
    year: 2022,
    offer: 'Новинка',
    decoration: 'Браслет',
    insert: 'Бриллиант',
    metall: 'Золото',
    image: './assets/catalog/bracelets/4.JPG',
  },
  { 
    name: 'Матинэ',
    price: 32,
    year: 2022,
    offer: 'Новинка',
    decoration: 'Браслет',
    insert: 'Жемчуг',
    metall: 'Серебро',
    image: './assets/catalog/bracelets/5.JPG',
  },
  { 
    name: 'Удача',
    price: 60,
    year: 2012,
    offer: 'Популярное',
    decoration: 'Браслет',
    insert: 'Фианит',
    metall: 'Золото',
    image: './assets/catalog/bracelets/6.JPG',
  },
  { 
    name: 'Аднойчы и назаужды',
    price: 63,
    year: 2022,
    offer: 'Новинка',
    decoration: 'Браслет',
    insert: 'Без вставки',
    metall: 'Серебро',
    image: './assets/catalog/bracelets/7.JPG',
  },
  { 
    name: 'Nail',
    price: 53,
    year: 2022,
    offer: 'Новинка',
    decoration: 'Браслет',
    insert: 'Бриллиант',
    metall: 'Серебро',
    image: './assets/catalog/bracelets/8.JPG',
  },
  { 
    name: 'Grid',
    price: 99,
    year: 2022,
    offer: 'Новинка',
    decoration: 'Браслет',
    insert: 'Без вставки',
    metall: 'Серебро',
    image: './assets/catalog/bracelets/9.JPG',
  },
  { 
    name: 'Leaves',
    price: 50,
    year: 2013,
    offer: 'Популярное',
    decoration: 'Браслет',
    insert: 'Бриллиант',
    metall: 'Серебро',
    image: './assets/catalog/bracelets/10.JPG',
  },
  { 
    name: 'Магия',
    price: 120,
    year: 2022,
    offer: 'Новинка',
    decoration: 'Цепочка',
    insert: 'Без вставки',
    metall: 'Серебро',
    image: './assets/catalog/chains/1.JPG',
  },
  { 
    name: 'Art',
    price: 102,
    year: 2014,
    offer: false,
    decoration: 'Цепочка',
    insert: 'Без вставки',
    metall: 'Серебро',
    image: './assets/catalog/chains/2.JPG',
  },
  { 
    name: 'Love',
    price: 157,
    year: 2015,
    offer: false,
    decoration: 'Цепочка',
    insert: 'Без вставки',
    metall: 'Золото',
    image: './assets/catalog/chains/3.JPG',
  },
  { 
    name: 'University style',
    price: 84,
    year: 2016,
    offer: 'Популярное',
    decoration: 'Цепочка',
    insert: 'Без вставки',
    metall: 'Серебро',
    image: './assets/catalog/chains/4.JPG',
  },
  { 
    name: 'Moon',
    price: 195,
    year: 2022,
    offer: 'Новинка',
    decoration: 'Цепочка',
    insert: 'Без вставки',
    metall: 'Золото',
    image: './assets/catalog/chains/5.JPG',
  },
  { 
    name: 'Закат',
    price: 116,
    year: 2022,
    offer: 'Новинка',
    decoration: 'Цепочка',
    insert: 'Жемчуг',
    metall: 'Золото',
    image: './assets/catalog/chains/6.JPG',
  },
  { 
    name: 'Инь & Янь',
    price: 185,
    year: 2017,
    offer: 'Популярное',
    decoration: 'Цепочка',
    insert: 'Жемчуг',
    metall: 'Золото',
    image: './assets/catalog/chains/7.JPG',
  },
  { 
    name: 'Сердце Эвереста',
    price: 110,
    year: 2022,
    offer: 'Новинка',
    decoration: 'Цепочка',
    insert: 'Фианит',
    metall: 'Золото',
    image: './assets/catalog/chains/8.JPG',
  },
  { 
    name: 'Sun',
    price: 115,
    year: 2022,
    offer: 'Новинка',
    decoration: 'Цепочка',
    insert: 'Бриллиант',
    metall: 'Золото',
    image: './assets/catalog/chains/9.JPG',
  },
  { 
    name: 'Fog',
    price: 144,
    year: 2018,
    offer: 'Популярное',
    decoration: 'Цепочка',
    insert: 'Бриллиант',
    metall: 'Серебро',
    image: './assets/catalog/chains/10.JPG',
  },
  { 
    name: 'Cloud',
    price: 126,
    year: 2019,
    offer: 'Популярное',
    decoration: 'Цепочка',
    insert: 'Фианит',
    metall: 'Серебро',
    image: './assets/catalog/chains/11.JPG',
  },
  { 
    name: 'Minimalism',
    price: 200,
    year: 2020,
    offer: 'Популярное',
    decoration: 'Цепочка',
    insert: 'Без вставки',
    metall: 'Золото',
    image: './assets/catalog/chains/12.JPG',
  },
  { 
    name: 'Pin',
    price: 67,
    year: 2021,
    offer: 'Популярное',
    decoration: 'Цепочка',
    insert: 'Фианит',
    metall: 'Серебро',
    image: './assets/catalog/chains/13.JPG',
  },
  { 
    name: 'Эверест',
    price: 183,
    year: 2010,
    offer: false,
    decoration: 'Серьги',
    insert: 'Без вставки',
    metall: 'Золото',
    image: './assets/catalog/earrings/1.JPG',
  },
  { 
    name: 'Рок',
    price: 176,
    year: 2011,
    offer: false,
    decoration: 'Серьги',
    insert: 'Без вставки',
    metall: 'Золото',
    image: './assets/catalog/earrings/2.JPG',
  },
  { 
    name: 'Изящность',
    price: 40,
    year: 2012,
    offer: false,
    decoration: 'Серьги',
    insert: 'Без вставки',
    metall: 'Золото',
    image: './assets/catalog/earrings/3.JPG',
  },
  { 
    name: 'Стиляга',
    price: 33,
    year: 2022,
    offer: 'Новинка',
    decoration: 'Серьги',
    insert: 'Без вставки',
    metall: 'Золото',
    image: './assets/catalog/earrings/4.JPG',
  },
  { 
    name: 'Листья',
    price: 64,
    year: 2013,
    offer: 'Популярное',
    decoration: 'Серьги',
    insert: 'Без вставки',
    metall: 'Золото',
    image: './assets/catalog/earrings/5.JPG',
  },
  { 
    name: 'Невеста',
    price: 190,
    year: 2014,
    offer: false,
    decoration: 'Серьги',
    insert: 'Фианит',
    metall: 'Золото',
    image: './assets/catalog/earrings/6.JPG',
  },
  { 
    name: 'Power',
    price: 34,
    year: 2022,
    offer: 'Новинка',
    decoration: 'Серьги',
    insert: 'Без вставки',
    metall: 'Серебро',
    image: './assets/catalog/earrings/7.JPG',
  },
  { 
    name: 'Elegance',
    price: 105,
    year: 2015,
    offer: false,
    decoration: 'Серьги',
    insert: 'Без вставки',
    metall: 'Золото',
    image: './assets/catalog/earrings/8.JPG',
  },
  { 
    name: 'Гвоздики',
    price: 180,
    year: 2022,
    offer: 'Новинка',
    decoration: 'Серьги',
    insert: 'Бриллиант',
    metall: 'Золото',
    image: './assets/catalog/earrings/9.JPG',
  },
  { 
    name: 'Замочек',
    price: 80,
    year: 2022,
    offer: 'Новинка',
    decoration: 'Серьги',
    insert: 'Фианит',
    metall: 'Золото',
    image: './assets/catalog/earrings/10.JPG',
  },
  { 
    name: 'Россыпь бриллиантов',
    price: 165,
    year: 2016,
    offer: 'Популярное',
    decoration: 'Серьги',
    insert: 'Бриллиант',
    metall: 'Серебро',
    image: './assets/catalog/earrings/11.JPG',
  },
  { 
    name: 'Square',
    price: 215,
    year: 2017,
    offer: 'Популярное',
    decoration: 'Серьги',
    insert: 'Фианит',
    metall: 'Серебро',
    image: './assets/catalog/earrings/12.JPG',
  },
  { 
    name: 'Капля росы',
    price: 218,
    year: 2018,
    offer: 'Популярное',
    decoration: 'Серьги',
    insert: 'Жемчуг',
    metall: 'Серебро',
    image: './assets/catalog/earrings/13.JPG',
  },
  { 
    name: 'Шик',
    price: 108,
    year: 2019,
    offer: 'Популярное',
    decoration: 'Серьги',
    insert: 'Без вставки',
    metall: 'Серебро',
    image: './assets/catalog/earrings/14.JPG',
  },
  { 
    name: 'Рим',
    price: 196,
    year: 2022,
    offer: 'Новинка',
    decoration: 'Заколка',
    insert: 'Без вставки',
    metall: 'Золото',
    image: './assets/catalog/hairpins/1.JPG',
  },
  { 
    name: 'Набор заколок',
    price: 37,
    year: 2022,
    offer: 'Новинка',
    decoration: 'Заколка',
    insert: 'Жемчуг',
    metall: 'Золото',
    image: './assets/catalog/hairpins/2.JPG',
  },
  { 
    name: 'Цветок',
    price: 66,
    year: 2021,
    offer: 'Популярное',
    decoration: 'Заколка',
    insert: 'Жемчуг',
    metall: 'Серебро',
    image: './assets/catalog/hairpins/3.JPG',
  },
  { 
    name: 'Coffee',
    price: 72,
    year: 2022,
    offer: 'Новинка',
    decoration: 'Заколка',
    insert: 'Жемчуг',
    metall: 'Серебро',
    image: './assets/catalog/hairpins/4.JPG',
  },
  { 
    name: 'Evening',
    price: 27,
    year: 2012,
    offer: false,
    decoration: 'Заколка',
    insert: 'Жемчуг',
    metall: 'Серебро',
    image: './assets/catalog/hairpins/5.JPG',
  },
  { 
    name: 'Булавка',
    price: 81,
    year: 2022,
    offer: 'Новинка',
    decoration: 'Заколка',
    insert: 'Без вставки',
    metall: 'Золото',
    image: './assets/catalog/hairpins/6.JPG',
  },
  { 
    name: 'Meeting',
    price: 93,
    year: 2022,
    offer: 'Новинка',
    decoration: 'Заколка',
    insert: 'Фианит',
    metall: 'Золото',
    image: './assets/catalog/hairpins/7.JPG',
  },
  { 
    name: 'Невидимка',
    price: 85,
    year: 2022,
    offer: 'Новинка',
    decoration: 'Заколка',
    insert: 'Бриллиант',
    metall: 'Серебро',
    image: './assets/catalog/hairpins/8.JPG',
  },
  { 
    name: 'Бабочка',
    price: 155,
    year: 2016,
    offer: 'Популярное',
    decoration: 'Заколка',
    insert: 'Фианит',
    metall: 'Серебро',
    image: './assets/catalog/hairpins/9.JPG',
  },
  { 
    name: 'Star',
    price: 86,
    year: 2022,
    offer: 'Новинка',
    decoration: 'Заколка',
    insert: 'Бриллиант',
    metall: 'Золото',
    image: './assets/catalog/hairpins/10.JPG',
  },
  { 
    name: 'Summer',
    price: 31,
    year: 2017,
    offer: 'Популярное',
    decoration: 'Заколка',
    insert: 'Фианит',
    metall: 'Золото',
    image: './assets/catalog/hairpins/11.JPG',
  },
  { 
    name: 'Zigzag',
    price: 184,
    year: 2019,
    offer: 'Популярное',
    decoration: 'Заколка',
    insert: 'Бриллиант',
    metall: 'Золото',
    image: './assets/catalog/hairpins/12.JPG',
  },
  { 
    name: 'Sweet',
    price: 76,
    year: 2020,
    offer: 'Популярное',
    decoration: 'Заколка',
    insert: 'Фианит',
    metall: 'Золото',
    image: './assets/catalog/hairpins/13.JPG',
  },
  { 
    name: 'Air',
    price: 125,
    year: 2022,
    offer: 'Новинка',
    decoration: 'Кольцо',
    insert: 'Бриллиант',
    metall: 'Серебро',
    image: './assets/catalog/rings/1.JPG',
  },
  { 
    name: 'Winter',
    price: 135,
    year: 2021,
    offer: 'Популярное',
    decoration: 'Кольцо',
    insert: 'Фианит',
    metall: 'Серебро',
    image: './assets/catalog/rings/2.JPG',
  },
  { 
    name: 'Together',
    price: 170,
    year: 2022,
    offer: 'Новинка',
    decoration: 'Кольцо',
    insert: 'Фианит',
    metall: 'Серебро',
    image: './assets/catalog/rings/3.JPG',
  },
  { 
    name: 'Engagement',
    price: 160,
    year: 2010,
    offer: false,
    decoration: 'Кольцо',
    insert: 'Бриллиант',
    metall: 'Серебро',
    image: './assets/catalog/rings/4.JPG',
  },
  { 
    name: 'Роскошь',
    price: 150,
    year: 2022,
    offer: 'Новинка',
    decoration: 'Кольцо',
    insert: 'Бриллиант',
    metall: 'Золото',
    image: './assets/catalog/rings/5.JPG',
  },
  { 
    name: 'Счастье',
    price: 145,
    year: 2011,
    offer: false,
    decoration: 'Кольцо',
    insert: 'Фианит',
    metall: 'Серебро',
    image: './assets/catalog/rings/6.JPG',
  },
  { 
    name: 'Spring',
    price: 140,
    year: 2012,
    offer: 'Популярное',
    decoration: 'Кольцо',
    insert: 'Фианит',
    metall: 'Золото',
    image: './assets/catalog/rings/7.JPG',
  },
  { 
    name: 'Life',
    price: 186,
    year: 2013,
    offer: false,
    decoration: 'Кольцо',
    insert: 'Фианит',
    metall: 'Серебро',
    image: './assets/catalog/rings/8.JPG',
  },
  { 
    name: 'Happy',
    price: 197,
    year: 2014,
    offer: 'Популярное',
    decoration: 'Кольцо',
    insert: 'Бриллиант',
    metall: 'Золото',
    image: './assets/catalog/rings/10.JPG',
  },
  { 
    name: 'Бесконечность',
    price: 30,
    year: 2022,
    offer: 'Новинка',
    decoration: 'Кольцо',
    insert: 'Без вставки',
    metall: 'Серебро',
    image: './assets/catalog/rings/11.JPG',
  },
  { 
    name: 'Находка',
    price: 55,
    year: 2022,
    offer: 'Новинка',
    decoration: 'Кольцо',
    insert: 'Жемчуг',
    metall: 'Золото',
    image: './assets/catalog/rings/12.JPG',
  },
  { 
    name: 'Королева',
    price: 65,
    year: 2015,
    offer: 'Популярное',
    decoration: 'Кольцо',
    insert: 'Без вставки',
    metall: 'Серебро',
    image: './assets/catalog/rings/13.JPG',
  },
  { 
    name: 'Old School',
    price: 75,
    year: 2016,
    offer: 'Популярное',
    decoration: 'Кольцо',
    insert: 'Жемчуг',
    metall: 'Золото',
    image: './assets/catalog/rings/14.JPG',
  },
  { 
    name: 'Мужское кольцо',
    price: 90,
    year: 2022,
    offer: 'Новинка',
    decoration: 'Кольцо',
    insert: 'Без вставки',
    metall: 'Золото',
    image: './assets/catalog/rings/15.JPG',
  },
  { 
    name: 'Помолвочное кольцо',
    price: 43,
    year: 2022,
    offer: 'Новинка',
    decoration: 'Кольцо',
    insert: 'Фианит',
    metall: 'Золото',
    image: './assets/catalog/rings/16.JPG',
  },
  { 
    name: 'Жемчужный омут',
    price: 69,
    year: 2022,
    offer: 'Новинка',
    decoration: 'Кольцо',
    insert: 'Жемчуг',
    metall: 'Золото',
    image: './assets/catalog/rings/17.JPG',
  },
  { 
    name: 'Обручальное кольцо',
    price: 83,
    year: 2017,
    offer: 'Популярное',
    decoration: 'Кольцо',
    insert: 'Без вставки',
    metall: 'Золото',
    image: './assets/catalog/rings/18.JPG',
  },
];